batch_size: 32
buffer_size: 1000
cuda: false
end_e: 0.01
env_id: FrozenLake-v1
exploration_fraction: 0.35
gamma: 0.95
is_slippery: false
learning_starts: 100
lr_input_scaling: 0.001
lr_weights: 0.001
num_envs: 1
num_layers: 5
num_qubits: 4
save_model: true
seed: null
start_e: 1.0
state_encoding: binary
target_network_frequency: 10
tau: 0.9
total_timesteps: 30000
train_frequency: 10
trial_name: 2025-06-20--11-09-37_dqn_qiskit_discrete
