ci:
    autoupdate_schedule: 'monthly'
    autofix_prs: false

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.11
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
